apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-stack-chatbot
  labels:
    app: llama-stack-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama-stack-chatbot
  template:
    metadata:
      labels:
        app: llama-stack-chatbot
    spec:
      containers:
      - name: chatbot
        image: llama-stack-chatbot:latest
        ports:
        - containerPort: 8000
        env:
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8000"
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: google-api-key
        - name: MCP_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: chatbot-config
              key: mcp-endpoint
        - name: MCP_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: mcp-auth-token
              optional: true
        - name: CORS_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: chatbot-config
              key: cors-origins
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Always
